version: "3"

services:
  dante:
    build: "./dante"
    ports:
      - "1080:1080"
    logging:
      driver: none
    restart: always

  openvpn:
    build: "./openvpn"
    ports:
      - "443:443"
    privileged: true
    logging:
      driver: none
    restart: always
