version: "3"
services:
    openvpn:
        build: "./openvpn"
        ports:
            - "443:443"
        logging:
            driver: none
        privileged: true
        restart: unless-stopped
