---
- name: Install openssl/openvpn
  sudo: yes
  apt: pkg={{ item }} state=present
  with_items:
    - openssl
    - openvpn

- name: Copy scripts
  sudo: yes
  copy: src={{ item.src }} dest={{ item.dest }} owner=root group=root mode=700
  with_items:
    - { src: generate-pems.sh, dest: ~/generate-pems.sh }
    - { src: create-client-config.sh, dest: ~/create-client-config.sh }

- name: Generate pems
  sudo: yes
  shell: ~/generate-pems.sh
  notify:
    - restart openvpn

- name: Create client config
  sudo: yes
  shell: ~/create-client-config.sh

- name: Write openvpn config
  sudo: yes
  template: src=openvpn.conf.j2 dest=/etc/openvpn/openvpn.conf
  notify:
    - restart openvpn

- name: Config iptables
  sudo: yes
  shell: iptables -t nat -A POSTROUTING -s 10.11.12.0/24 -o eth0 -j MASQUERADE
